### ISSUE TITLE
What happens when we declare a payment on an in-memory request?

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1441]
# Problem

If you declare a payment on an in-memory request, will it try to write the `declareSentPayment` action to IPFS even though the `create` action never persisted? If so, that's a problem and needs to be fixed.

**Comment by aimensahnoun** [comment]
A small test of trying to declare payment in an in-memory request shows that it fails because the method tries to read the content of the request from IPFS first, and since the request has yet to be persisted, it cannot find it and errors out.

![Result of trying to declare payment in an in-memory request](https://github.com/user-attachments/assets/0a07979e-273d-4193-a2b2-024cf8f513b2)

It is safe to assume that the same thing would happen to any action that behaves in the same way (read from IPFS and then attach an update)
